window.GAMES_DATA = [
  {
    id: "snake",
    title: "Snake",
    slug: "snake",
    category: "Arcade",
    tags: ["Classic", "Arcade", "Retro", "Skill"],
    desc: "Guide your snake around the board, eat the food, and grow as long as you can without hitting a wall or yourself.",
    thumb: "games/snake/thumb.svg",
    url: "games/snake/index.html",
    w: 400, h: 400
  },
  {
    id: "2048",
    title: "2048",
    slug: "2048",
    category: "Puzzle",
    tags: ["Puzzle", "Numbers", "Strategy", "Classic"],
    desc: "Slide and combine matching tiles to reach the elusive 2048 tile. Simple to learn, hard to put down.",
    thumb: "games/2048/thumb.svg",
    url: "games/2048/index.html",
    w: 400, h: 400
  },
  {
    id: "memory",
    title: "Memory Match",
    slug: "memory",
    category: "Puzzle",
    tags: ["Memory", "Puzzle", "Cards", "Brain"],
    desc: "Flip cards two at a time and find every matching pair in as few moves as possible.",
    thumb: "games/memory/thumb.svg",
    url: "games/memory/index.html",
    w: 420, h: 420
  },
  {
    id: "tictactoe",
    title: "Tic-Tac-Toe",
    slug: "tictactoe",
    category: "Strategy",
    tags: ["Strategy", "Classic", "Two Player", "AI"],
    desc: "Take on an unbeatable AI in the timeless game of X's and O's. Can you force a draw?",
    thumb: "games/tictactoe/thumb.svg",
    url: "games/tictactoe/index.html",
    w: 320, h: 320
  },
  {
    id: "breakout",
    title: "Breakout",
    slug: "breakout",
    category: "Arcade",
    tags: ["Arcade", "Classic", "Ball", "Bricks"],
    desc: "Bounce the ball off your paddle to smash every brick on the board without letting it fall.",
    thumb: "games/breakout/thumb.svg",
    url: "games/breakout/index.html",
    w: 420, h: 420
  },
  {
    id: "minesweeper",
    title: "Minesweeper",
    slug: "minesweeper",
    category: "Puzzle",
    tags: ["Puzzle", "Logic", "Classic", "Brain"],
    desc: "Clear the board without detonating a mine — use the numbers to figure out where it's safe to click.",
    thumb: "games/minesweeper/thumb.svg",
    url: "games/minesweeper/index.html",
    w: 380, h: 380
  },
  {
    id: "whackamole",
    title: "Whack-a-Mole",
    slug: "whackamole",
    category: "Arcade",
    tags: ["Arcade", "Reflex", "Fast-Paced", "Fun"],
    desc: "Moles pop up fast — whack as many as you can before the 30-second timer runs out.",
    thumb: "games/whackamole/thumb.svg",
    url: "games/whackamole/index.html",
    w: 360, h: 360
  },
  {
    id: "flappy",
    title: "Flappy Block",
    slug: "flappy",
    category: "Arcade",
    tags: ["Arcade", "Reflex", "Endless", "Challenging"],
    desc: "Tap to flap and weave through the gaps without crashing. One of the toughest games on the site.",
    thumb: "games/flappy/thumb.svg",
    url: "games/flappy/index.html",
    w: 360, h: 480
  },
  {
    id: "simon",
    title: "Simon Says",
    slug: "simon",
    category: "Skill",
    tags: ["Memory", "Skill", "Sound", "Brain"],
    desc: "Watch the growing pattern of lights and sounds, then repeat it back exactly. How far can you go?",
    thumb: "games/simon/thumb.svg",
    url: "games/simon/index.html",
    w: 340, h: 340
  },
  {
    id: "fifteen",
    title: "15 Puzzle",
    slug: "fifteen",
    category: "Puzzle",
    tags: ["Puzzle", "Numbers", "Classic", "Sliding"],
    desc: "Slide the numbered tiles around the grid to put them back in order, from 1 all the way to 15.",
    thumb: "games/fifteen/thumb.svg",
    url: "games/fifteen/index.html",
    w: 360, h: 360
  },
  {
    id: "mathsprint",
    title: "Math Sprint",
    slug: "mathsprint",
    category: "Skill",
    tags: ["Math", "Skill", "Timed", "Brain"],
    desc: "Solve as many quick arithmetic problems as you can before the 60-second clock runs out.",
    thumb: "games/mathsprint/thumb.svg",
    url: "games/mathsprint/index.html",
    w: 360, h: 360
  },
  {
    id: "rps",
    title: "Rock Paper Scissors",
    slug: "rps",
    category: "Strategy",
    tags: ["Classic", "Strategy", "Two Player", "Fun"],
    desc: "The playground classic — go head to head against the computer across endless rounds.",
    thumb: "games/rps/thumb.svg",
    url: "games/rps/index.html",
    w: 340, h: 340
  },
  {
    id: "pong",
    title: "Pong",
    slug: "pong",
    category: "Arcade",
    tags: ["Arcade", "Classic", "Two Player", "Retro"],
    desc: "The original video game — rally the ball past the AI paddle. First to 7 points wins.",
    thumb: "games/pong/thumb.svg",
    url: "games/pong/index.html",
    w: 480, h: 320
  },
  {
    id: "spacedefender",
    title: "Space Defender",
    slug: "spacedefender",
    category: "Arcade",
    tags: ["Arcade", "Shooter", "Retro", "Action"],
    desc: "Blast wave after wave of descending invaders before they reach your ship. How many waves can you clear?",
    thumb: "games/spacedefender/thumb.svg",
    url: "games/spacedefender/index.html",
    w: 420, h: 480
  },
  {
    id: "connectfour",
    title: "Connect Four",
    slug: "connectfour",
    category: "Strategy",
    tags: ["Strategy", "Classic", "Two Player", "AI"],
    desc: "Drop pieces to connect four in a row — across, down, or diagonally — before the AI beats you to it.",
    thumb: "games/connectfour/thumb.svg",
    url: "games/connectfour/index.html",
    w: 420, h: 420
  },
  {
    id: "sudoku",
    title: "Sudoku",
    slug: "sudoku",
    category: "Puzzle",
    tags: ["Puzzle", "Numbers", "Logic", "Classic"],
    desc: "Fill the grid so every row, column and 3x3 box contains 1 through 9 exactly once.",
    thumb: "games/sudoku/thumb.svg",
    url: "games/sudoku/index.html",
    w: 380, h: 380
  },
  {
    id: "wordguess",
    title: "Word Guess",
    slug: "wordguess",
    category: "Word",
    tags: ["Word", "Puzzle", "Vocabulary", "Daily"],
    desc: "Guess the hidden 5-letter word in 6 tries. Green means right spot, yellow means wrong spot.",
    thumb: "games/wordguess/thumb.svg",
    url: "games/wordguess/index.html",
    w: 420, h: 500
  },
  {
    id: "hangman",
    title: "Hangman",
    slug: "hangman",
    category: "Word",
    tags: ["Word", "Vocabulary", "Classic", "Brain"],
    desc: "Guess the hidden word one letter at a time across animals, countries, food and space categories.",
    thumb: "games/hangman/thumb.svg",
    url: "games/hangman/index.html",
    w: 420, h: 480
  },
  {
    id: "reaction",
    title: "Reaction Test",
    slug: "reaction",
    category: "Skill",
    tags: ["Skill", "Reflex", "Timed", "Fast-Paced"],
    desc: "Wait for the panel to turn green and tap as fast as you can. Five rounds, measured in milliseconds.",
    thumb: "games/reaction/thumb.svg",
    url: "games/reaction/index.html",
    w: 380, h: 400
  },
  {
    id: "colorrush",
    title: "Color Rush",
    slug: "colorrush",
    category: "Skill",
    tags: ["Skill", "Reflex", "Timed", "Brain"],
    desc: "Tap the ink color a word is printed in — not what it says. Beat the 45-second clock without slipping up.",
    thumb: "games/colorrush/thumb.svg",
    url: "games/colorrush/index.html",
    w: 380, h: 380
  },
  {
    id: "asteroids",
    title: "Asteroids",
    slug: "asteroids",
    category: "Arcade",
    tags: ["Arcade", "Classic", "Space", "Retro"],
    desc: "Rotate, thrust and blast your way through waves of drifting asteroids before they wear down your ship.",
    thumb: "games/asteroids/thumb.svg",
    url: "games/asteroids/index.html",
    w: 460, h: 460
  },
  {
    id: "blockdrop",
    title: "Block Drop",
    slug: "blockdrop",
    category: "Puzzle",
    tags: ["Puzzle", "Classic", "Blocks", "Arcade"],
    desc: "Rotate and stack falling blocks to clear lines. Speed ramps up every level — how high can you climb?",
    thumb: "games/blockdrop/thumb.svg",
    url: "games/blockdrop/index.html",
    w: 200, h: 400
  },
  {
    id: "bubbleshooter",
    title: "Bubble Shooter",
    slug: "bubbleshooter",
    category: "Puzzle",
    tags: ["Puzzle", "Aim", "Colors", "Classic"],
    desc: "Aim and shoot to match 3 or more same-colored bubbles. Clear the board before it reaches the bottom.",
    thumb: "games/bubbleshooter/thumb.svg",
    url: "games/bubbleshooter/index.html",
    w: 280, h: 460
  },
  {
    id: "checkers",
    title: "Checkers",
    slug: "checkers",
    category: "Strategy",
    tags: ["Strategy", "Classic", "Two Player", "AI"],
    desc: "Jump and capture your way across the board against a real AI opponent. Captures are mandatory — plan ahead.",
    thumb: "games/checkers/thumb.svg",
    url: "games/checkers/index.html",
    w: 400, h: 400
  },
  {
    id: "match3",
    title: "Match-3 Gems",
    slug: "match3",
    category: "Puzzle",
    tags: ["Puzzle", "Colors", "Matching", "Score Attack"],
    desc: "Swap adjacent gems to line up 3 or more of a kind. You've got 20 moves to rack up the highest score.",
    thumb: "games/match3/thumb.svg",
    url: "games/match3/index.html",
    w: 380, h: 380
  },
  {
    id: "solitaire",
    title: "Solitaire",
    slug: "solitaire",
    category: "Cards",
    tags: ["Cards", "Classic", "Solo", "Strategy"],
    desc: "The classic Klondike solitaire — build down in alternating colors and get every card home to the foundations.",
    thumb: "games/solitaire/thumb.svg",
    url: "games/solitaire/index.html",
    w: 480, h: 400
  },
  {
    id: "trivia",
    title: "Trivia Quiz",
    slug: "trivia",
    category: "Skill",
    tags: ["Trivia", "Brain", "Timed", "Knowledge"],
    desc: "Ten rapid-fire multiple choice questions across geography, science, history and more. Beat the clock on each one.",
    thumb: "games/trivia/thumb.svg",
    url: "games/trivia/index.html",
    w: 420, h: 420
  },
  {
    id: "typingtest",
    title: "Typing Speed Test",
    slug: "typingtest",
    category: "Skill",
    tags: ["Skill", "Typing", "Timed", "Practice"],
    desc: "Type the given sentence as fast and accurately as you can. Tracks your words-per-minute and accuracy.",
    thumb: "games/typingtest/thumb.svg",
    url: "games/typingtest/index.html",
    w: 500, h: 320
  },
  {
    id: "candyduel",
    title: "Candy Duel",
    slug: "candyduel",
    category: "Multiplayer",
    tags: ["Multiplayer", "Two Player", "AI", "Colors", "Match-3"],
    desc: "A head-to-head candy match game — take turns matching candies for points. Play vs the computer or pass the device to a friend.",
    thumb: "games/candyduel/thumb.svg",
    url: "games/candyduel/index.html",
    w: 380, h: 460
  },
  {
    id: "airhockey",
    title: "Air Hockey",
    slug: "airhockey",
    category: "Multiplayer",
    tags: ["Multiplayer", "Two Player", "AI", "Arcade", "Sports"],
    desc: "Fast-paced air hockey — drag your mallet to block and strike. Play vs the computer or share the screen with a friend. First to 7 wins.",
    thumb: "games/airhockey/thumb.svg",
    url: "games/airhockey/index.html",
    w: 300, h: 480
  },
  {
    id: "mazerunner",
    title: "Maze Runner",
    slug: "mazerunner",
    category: "Puzzle",
    tags: ["Puzzle", "Maze", "Timed", "Skill"],
    desc: "A brand-new maze every time — navigate from the top-left to the exit as fast as you can and chase your best time.",
    thumb: "games/mazerunner/thumb.svg",
    url: "games/mazerunner/index.html",
    w: 320, h: 320
  },
  {
    id: "towerstack",
    title: "Tower Stack",
    slug: "towerstack",
    category: "Arcade",
    tags: ["Arcade", "Timing", "Skill", "Endless"],
    desc: "Drop each swinging block to line it up with the tower below. Miss too much and it's over — how high can you build?",
    thumb: "games/towerstack/thumb.svg",
    url: "games/towerstack/index.html",
    w: 320, h: 480
  }
];

window.CATEGORIES = [
  { name: "Arcade", count: 8 },
  { name: "Puzzle", count: 9 },
  { name: "Strategy", count: 4 },
  { name: "Skill", count: 6 },
  { name: "Word", count: 2 },
  { name: "Cards", count: 1 },
  { name: "Multiplayer", count: 2 }
];
